/// Flutter icons TwitterSpace
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TwitterSpace
///      fonts:
///       - asset: fonts/TwitterSpace.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TwitterSpace {
  TwitterSpace._();

  static const _kFontFam = 'TwitterSpace';
  static const String? _kFontPkg = null;

  static const IconData emotionadd = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData micoff = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitterspace = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
